version: '3.8'

services:
  newsproject:
    build: ./
    command: python manage.py runserver
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_PASSWORD=123456

  db:
    restart: always
    image: postgres.latest
    environment:
      - POSTGRES_PASSWORD=123456
    ports:
      - "5436:5432"